CREATE TABLE IF NOT EXISTS Node (
    NodeID INTEGER PRIMARY KEY AUTOINCREMENT,
    NodeTitle VARCHAR(100) NOT NULL,
    NodeType VARCHAR(50) NOT NULL CHECK(NodeType IN('image', 'text', 'link')),
    Tags TEXT,
    Content TEXT,
    embedding TEXT,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Edge(
    EdgeID INTEGER PRIMARY KEY AUTOINCREMENT,
    OutNode INTEGER NOT NULL,
    InNode INTEGER NOT NULL,
    Relationship VARCHAR(50) NOT NULL,
    FOREIGN KEY (OutNode) REFERENCES Node(NodeID),
    FOREIGN KEY (InNode) REFERENCES Node(NodeID)
);
